### ISSUE TITLE
Why isn't nulloptions the default codec for Options?

### ISSUE THREAD

**Issue by bilal-fazlani** [sirthias/borer#123]
https://sirthias.github.io/borer/borer-core/nullable-and-default.html#nulloptions

This looks like an ideal way to encode and decode optional values

`null` IMO, better represents absence of a value compared to and empty array `[]` in json world.
I don't have much knowledge about CBOR but I have a feeling that cbor would also have something similar to null which represents absence of a value.

I would vote for this becoming the default codec for Options. Unless I am missing something obvious. What are your thoughts @sirthias ?

**Comment by sirthias** [comment]
Thank you, @bilal-fazlani, for this very good question, that I should really address in the documentation!

The reason that `NullOptions` isn't the default is that it is _unsound_ as in "it doesn't compose properly". Consider the type `Option[Option[String]]` and a respective value of `Some(None)`. With `NullOptions` this serializes to `null` and deserializes to `None` rather than `Some(None)`, which is clearly unsound as it violates the basic roundtrip requirement `deserialize(serialize(x)) == x`.

When we built `spray-json` in 2011 then this exact problem was one of the first issues that came up: https://github.com/spray/spray-json/issues/7

**Comment by sirthias** [comment]
Just added a note to the docs at https://sirthias.github.io/borer/borer-core/nullable-and-default.html#nulloptions.
Thank you again for bringing this up, @bilal-fazlani!

**Comment by bilal-fazlani** [comment]
Ohh yeah that makes sense. Thanks for the clarification!
