### ISSUE TITLE
Cbor to Json conversion does not work for List[T]

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#143]
**Test**

```scala
case class A(x: Int)

implicit lazy val aCodec: Codec[A] = MapBasedCodecs.deriveCodec

val byteArray = Cbor.encode(List(A(10))).toByteArray
val dom       = Cbor.decode(byteArray).to[Element].value
Json.encode(dom).toUtf8String
```

```txt
Exception in thread "main" io.bullet.borer.Borer$Error$Unsupported: The JSON renderer doesn't support definite-length maps (Output.ToByteArray index 1)
```

**Comment by sirthias** [comment]
The reason for this effect is that the CBOR renderer encodes the `A` instance to a "sized array", i.e. an array with a fixed size. When decoded into the DOM this is accurately represented and the serialization to JSON fails because JSON doesn't support fixed-size arrays or maps.

More generally since JSON is a subset of CBOR and not the other way around, i.e. there are constructs in CBOR that have no direct counterpart in JSON, a CBOR-to-JSON is not generally possible.

What would be required is a general translation logic that somehow maps the CBOR constructs that have no direct counterparts in JSON to some alternative JSON constructs.
For example the following conversions would do:

- `undefined` to `null`
- `Float16` to `Float` which would then be written to JSON numbers
- byte strings and byte string streams to a base64-encoded JSON Strings
- raw text bytes and raw text byte streams to JSON Strings
- sized arrays to unsized arrays
- sized maps to unsized maps
- ignore/drop tags
- simple values to JSON numbers

This is of course not the only possible conversion logic because there is no single truth here.
What borer _could_ provide is some kind of transformation logic on the `Dom.Element` level, which applies the logic above but is "overridable" with custom logic where necessary.

So the process would be

```
CBOR --decoding--> DOM --transformation--> DOM --encoding--> JSON
```

Is that something that would work for you?
```

**Comment by mushtaq** [comment]
Oh, I see. I thought it arises only for List[A], but as you explained it will also be the case just for an instance of A.

I came across this behaviour only in attempt to debug some other issue with CBOR, so I don't really need this in the production code. In such cases your suggested solution will be more than fine. Not very critical for me.
