### ISSUE TITLE
AdtEncodingStrategy.flat() does not work for recursive ADTs

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#144]
**Test**

```scala
sealed trait Msg
sealed trait Request                  extends Msg
case class Start(x: Int)              extends Request
case class Stop(x: Int)               extends Request
case class Response(request: Request) extends Msg

implicit val flatAdtEncoding: AdtEncodingStrategy = AdtEncodingStrategy.flat()

implicit lazy val msgCodec: Codec[Msg]         = MapBasedCodecs.deriveCodec
implicit lazy val requestCodec: Codec[Request] = MapBasedCodecs.deriveCodec
implicit lazy val responseCodec: Codec[Response] = MapBasedCodecs.deriveCodec
implicit lazy val startCodec: Codec[Start] = MapBasedCodecs.deriveCodec
implicit lazy val stopCodec: Codec[Stop]   = MapBasedCodecs.deriveCodec

val msg: Msg = Start(100)

val byteArray = Json.encode(msg).toByteArray
Json.decode(byteArray).to[Msg].value
```

**Exception**

```txt
Exception in thread "main" io.bullet.borer.Borer$Error$Unsupported: AdtEncodingStrategy.flat
requires all sub-types of `msocket.example.server.Msg` be serialized as a Map but here it was a 
String (Output.ToByteArray index 18)
```

**Comment by mushtaq** [comment]
Maybe this can be further simplified (without recursion) to:

```scala
sealed trait Msg
sealed trait Request     extends Msg
case class Start(x: Int) extends Request

implicit val flatAdtEncoding: AdtEncodingStrategy = AdtEncodingStrategy.flat()

implicit lazy val msgCodec: Codec[Msg]         = MapBasedCodecs.deriveCodec
implicit lazy val requestCodec: Codec[Request] = MapBasedCodecs.deriveCodec
implicit lazy val startCodec: Codec[Start]     = MapBasedCodecs.deriveCodec

val msg: Msg = Start(100)

val byteArray = Json.encode(msg).toByteArray
Json.decode(byteArray).to[Msg].value
```

**Comment by sirthias** [comment]
Thank you once again for reporting, @mushtaq.
While https://github.com/sirthias/borer/commit/5e5262944a2e8766e9bd45b935d4f40e467b4b1a fixes the immediate problem it's not a full solution yet.

This issue once again shows that the flat ADT encoding strategy is fundamentally flawed.

Consider the following ADT which has an intermediate abstract level with a recursion:

```scala
sealed trait A
sealed trait B             extends A
case class C(x: Option[B]) extends B
```

In order to break the recursion we need to explicitly define the codec for `B` in addition to the one for `A`:

```scala
implicit lazy val bCodec: Codec[B] = MapBasedCodecs.deriveAllCodecs[B]
implicit val aCodec                = MapBasedCodecs.deriveAllCodecs[A]
```

Since, so far, codec layers are completely independent the value `C(None)` will be encoded to the following JSON value under the default ADT encoding strategy:

```json
{
  "B": {
    "C": {
      "x":[]
    }
  }
}
```

So we have two stacked type-id envelopes!
This 1st one tells the `Decoder[A]` that the value is a `B` and the 2nd one tells the `Decoder[B]` that the value is `C`.
While maybe not the most efficient this is perfectly fine and robust.

However, with the flat encoding strategy (and the fix from https://github.com/sirthias/borer/commit/5e5262944a2e8766e9bd45b935d4f40e467b4b1a) `C(None)` is now encoded to:

```json
{
  "_type": "B",
  "_type": "C",
  "x":[]
}
```

which happens to round-trip successfully with borer itself but is clearly problematic.

The flat ADT encoding strategy doesn't compose and as such doesn't allow for one value to be tagged with two stacked type-ids as the stacked codecs for `A` and `B` require.

Unfortunately there doesn't appear to be a great and clean solution to this problem.
The best I can currently think of is to merge the two stacked type-ids into a single one with an array, so sth like:

```json
{
  "_type": ["B", "C"],
  "x":[]
}
```

But that would certainly trip up other external systems which expect the type-id to be a single string value.

What do you think?

**Comment by sirthias** [comment]
Just created https://github.com/sirthias/borer/issues/145 to track progress on solving this issue properly and completely.

**Comment by mushtaq** [comment]
Commented on #145
