### ISSUE TITLE
Avoid stacked type ids when encoding ADTs with intermediate level abstract recursions

### ISSUE THREAD

**Issue by sirthias** [sirthias/borer#145]
Consider the following ADT which has an intermediate abstract level with a recursion:

```scala
sealed trait A
sealed trait B             extends A
case class C(x: Option[B]) extends B
```

In order to break the recursion we need to explicitly define the codec for `B` in addition to the one for `A`:

```scala
implicit lazy val bCodec: Codec[B] = MapBasedCodecs.deriveAllCodecs[B]
implicit val aCodec                = MapBasedCodecs.deriveAllCodecs[A]
```

Since, so far, codec layers are completely independent the value `C(None)` will be encoded to the following JSON value under the default ADT encoding strategy:

```json
{
  "B": {
    "C": {
      "x":[]
    }
  }
}
```

So we have two stacked type-id envelopes!
This 1st one tells the `Decoder[A]` that the value is a `B` and the 2nd one tells the `Decoder[B]` that the value is `C`.

While this kind of type-id stacking isn't necessarily a problem by itself it has two issues:

1. It's not as efficient as it could be. Since the ADT is statically known the inner type id alone ("C" in the example above) would be enough to tell the `Decoder[A]` that it should forward decoding to the `Decoder[B]`.

2. Stacked type-ids don't play well with `AdtEncodingStrategy.flat`. Currently they result in sth like this:

    ```json
    {
      "_type": "B",
      "_type": "C",
      "x":[]
    }
    ```

    which is clearly problematic even though it happens to round-trip successfully with borer itself.

This ticket proposes to only render the inner-most type id in all cases where the current logic would render stacked ids.

**Comment by mushtaq** [comment]
> This ticket proposes to only render the inner-most type id in all cases where the current logic would render stacked ids.

Yes, I agree that this is the best solution. I am also ok, if we just throw exception/compile time error for the recursive ADTs + flat encoding. In those rare cases we will be fine to handle the nested JSON.

Personally, I have started liking the default nested ADT encoding a lot. One of the arguments in favour of flat encoding came because of Typescript. 

TS does not have inbuilt pattern-matching feature, but if ADTs are encoded flat, there is a very reasonable workaround which gives most of the benefits of pattern matching as [described here](https://blog.logrocket.com/pattern-matching-and-type-safety-in-typescript-1da1231a2e34/).

We also thought of writing a generic procedure in TS to flatten the response JSON, but ran into problems (on the TS side the types are structural interfaces, which can not hold any data hints). I really wish TS allowed us pattern match with nested data.

**Comment by sirthias** [comment]
Ok, interesting. Thank you for the pointer!
