### ISSUE TITLE
getting Encoder via Codec does not always work

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#24]
Test

```scala
def getEncoder[T](implicit x: Encoder[Array[T]]): Encoder[Array[T]] = x

val enc: Encoder[Array[java.lang.Byte]] = Encoder.forByteArray.contramap(_.map(x ⇒ x: Byte))
val dec: Decoder[Array[java.lang.Byte]] = Decoder.forByteArray.map(_.map(x ⇒ x: java.lang.Byte))

implicit val codec: Codec[Array[java.lang.Byte]] = Codec(enc, dec)

assert(getEncoder[java.lang.Byte] eq enc)
```

**Comment by sirthias** [comment]
Getting an `Encoder[T]` via a `Codec[T]` _does_ always work.
The problem here is that implicit resolution doesn't choose the alternative that you want over another one that also makes the types line up.

In your example the compiler has these two alternatives for supplying the missing implicit argument to `getEncoder`:

```scala
getEncoder[java.lang.Byte](Encoder.fromCodec)
getEncoder[java.lang.Byte](Encoder.forArray)
```

You would like the compiler to pick the first alternative, but it chooses the second.
The reason for this is somewhat hidden in the implicit resolution precedence rules, which were nicely described in [this blogpost](http://eed3si9n.com/implicit-parameter-precedence-again) more than 7 years ago (crazy, how time flies).

Since both alternatives are at the same level in implicit scope the compiler applies the static overloading rules for disambiguation and picks `forArray` over `fromCodec` because `forArray` is more specific.

What this means is that you cannot use an implicit `Codec` to "override" one of the predefined Encoders/Decoders, without inserting an explicit `Encoder.fromCodec` or `Decoder.fromCodec` somewhere. Since a `Codec` is really an alternative and somewhat "lower priority" packaging of encoders and decoders I don't think there is anything that can be done to easily fix this.

However, the solution is relatively simply:
If you want to "override" predefined Encoders/Decoders, you need to do it by directly making implicit Encoders/Decoders available or insert an explicit `fromCodec`.
