### ISSUE TITLE
Ability to inject extra fields into derived codec

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#289]
**Use case**

We represent domain errors as ADTs extending RuntimeException like this:

```scala
sealed abstract class DomainError(msg: String) extends RuntimeException(msg)

object DomainError {
  case class RegistrationFailed(componentName: String) extends DomainError(s"registration failed for component: $componentName")
  case class RegistrationListingFailed()               extends DomainError(s"unable to get the list of registered locations")
}
```

Encoding and decoding this ADT using `MapBasedCodecs.deriveAllCodecs` works great when producer and consumer both are Scala programs. But, Javascript consumers are also interested an additional `error_message` field in the json that captures the value of `Throwable.getMessage`.

So, we write the codecs as follows:

```scala
implicit lazy val flatAdtEncoding: AdtEncodingStrategy = AdtEncodingStrategy.flat()
implicit lazy val domainErrorCodec: Codec[DomainError] = CodecHelpers.enrich(MapBasedCodecs.deriveAllCodecs)
```

Where, `CodecHelpers.enrich` is implemented this way:

```scala
object CodecHelpers {
  def enrich[T <: Throwable](defaultCodec: Codec[T]): Codec[T] = {
    Codec(enrich(defaultCodec.encoder), defaultCodec.decoder)
  }

  def enrich[E <: Throwable](encoder: Encoder[E]): Encoder[E] = {
    Encoder[Map[String, Element]].contramapWithWriter { (w, error) =>
      val bytes   = w.target.encode(error)(encoder).toByteArray
      val mapElem = w.target.decode(bytes).to[Map[String, Element]].value
      mapElem + ("error_message" -> StringElem(error.getMessage))
    }
  }
}
```

This method has to do 2 passes during encoding: 
- first converting to an intermediate DOM Element so that extra field can be added
- and then converting it to Json during Json.encode

Is there any way to avoid that? I went through `Writer` APIs to see if alternate solution is possible, but can't figure out any.

**Comment by sirthias** [comment]
I see the problem.

In these types of cases AST-based serialization solutions have the benefit that you can wrap existing encoders and easily modify their output before passing the generated AST down to the actual AST-to-bytes layer.
Since _borer_ is AST-less this is not easily possible.

One work-around would be to simply _wrap_ the serialized DomainError in another JSON object, which also contains the error message. If you also control the JS side of your application this might be the cleanest.

Another work-around would be to use the new "encoder concatenation" feature, which I just added.
With it your `CodecHelpers` object would look like this:

```scala
object CodecHelpers {
  def enrich[T <: Throwable](defaultCodec: Codec[T]): Codec[T] =
    defaultCodec.withEncoder {
      defaultCodec.encoder.concat { (w, error) =>
        w.writeMapHeader(1) ~ "error_message" ~ error.getMessage
      }
    }
}
```

**Comment by sirthias** [comment]
I'm going to publish another release right away, containing this new feature.
The last one is already a bit old... :)

**Comment by mushtaq** [comment]
Wow, fantastic, thank you so much!
Going to upgrade right away.
