### ISSUE TITLE
Flat encoding for the ADTs

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#38]
We have successfully managed to use single set of user defined (map-based) codecs for a small subset of our domain models and achieve 3 distinct tasks: send them in akka-remote message payloads (CBOR), send some of them to Redis (CBOR) and serve them via http (JSON). 

We are very happy with the outcome and looking forward to the possibility of replacing 3 different libraries (chill, scalapb and play-json) with a single library. 

One feedback from the team is around `nested` encoding of ADTs which becomes apparent mainly during the Json output as:

```json
{ 
  "Dog" :  {
      "age": 10,
      "name": "gabbar"
   }
}
```

Will it be possible to add a configuration which allows it to be encoded `flat` as below? Consuming this from say a python library is much easier it seems (cc/ @abrighton)

```json
{ 
   "type": "Dog",
   "age": 10,
   "name": "gabbar"
}
```

**Comment by plokhotnyuk** [comment]
Almost all JSON libraries for Scala have ability to switch between these encodings for sum types. Also, they have ability to override the default key of the discriminator field ("type" in the sample above) and its values ("Dog", "Cat", etc.).

**Comment by sirthias** [comment]
Yes, ok.
This shouldn't be hard to implement.

**Comment by sirthias** [comment]
@mushtaq One question: In your use cases, would the `"type"` member always be the first member in the serialization or would you have to support also sth like:

```json
{ 
   "age": 10,
   "type": "Dog",
   "name": "gabbar"
}
```

?

**Comment by plokhotnyuk** [comment]
Circe serializes "type" field in the end of the JSON object, while others (play-json, upickle, jackson, AVSystem GenCodec, jsoniter-scala) serialize it in the beginning.

**Comment by sirthias** [comment]
ok, thank you for this info @plokhotnyuk.
So far borer's decoding strategy is a simple, monotonic single-pass across the input.
Supporting "type" fields somewhere buried in the stream of object members requires potentially unbounded caching, which is sth that I would like to avoid...

**Comment by bilal-fazlani** [comment]
"An object is an **unordered** set of name/value pairs. " (Source http://json.org/)

**Comment by mushtaq** [comment]
> @mushtaq One question: In your use cases, would the `"type"` member always be the first member in the serialization or would you have to support also sth like:
> 
> ```json
> { 
>    "age": 10,
>    "type": "Dog",
>    "name": "gabbar"
> }
> ```
> 
> ?

For us, the order does not matter. Having type as a first element is perfectly fine.

**Comment by sirthias** [comment]
@bilal-fazlani Yes, that is why the "flat" encoding of type ids is problematic.
We could have a 1GB JSON file containing the id of "what type to deserialize into" as the very last bytes, which would mean that either

- the whole file has to be decoded without knowing the target type (i.e. an intermediate representation, like an AST, is required)

- or multiple parsing passes are required.

Neither is an attractive choice.

However, _borer_ can relatively easily support the "flat" style requested in this ticket with the limitation that the "type" member has to be the first member.

**Comment by bilal-fazlani** [comment]
I understand the rationale for the limitation now. Thanks for sharing context in detail.

**Comment by abrighton** [comment]
As long as all the clients are using borer, this limitation ('type' as first key) would be OK, but I don't think you can be sure that 'type' is the first item in JSON or CBOR generated using other languages or libraries. The order of the keys will likely be random.

**Comment by mushtaq** [comment]
@sirthias I tested that `upickle` allows `$type` field to appear anywhere in the JSON object while parsing. I thought `upickle` also has a streaming parser, not sure how it manages that.

**Comment by sirthias** [comment]
Yes, it is of course _possible_ to support the special member at an arbitrary position.
But it's _not_ possible to do this in bounded memory without a second pass over the input.

The whole approach of encoding the ADT subtype with an additional "type" member is flawed, for at least these three reasons:

1. It conflates two conceptually well separated and distinct name spaces: The one of the envelope (ADT) and the one of the sub-type. This always leads to the risk of name collisions, which gives rise to "$type" or "__type" or sth similar, which make the smell even more visible.

2. Due the "unordered" nature of JSON objects/maps it makes efficient parsing impossible in the general case, since the information, how to _interpret_ an object's members (the _type_ of the object) might be delayed until the very end of the input file.

3. It uses more bytes than _borers_ default approach, i.e. it's also less efficient storage-wise.

The only benefit (and probably the reason why someone chose this inferior design (from a strongly typed POV) in the first place) is that a JSON snippet can be deserialized as the super-type _or_ the sub-type, i.e. the encodings are compatible between the two (as long as surplus members are simply being ignored).
However, I would argue that this probably appears like a benefit only in weakly typed / dynamic environments.
In Scala I would argue that it's actually a drawback as it doesn't "fail fast" in the case of type mismatches.

So, my preferred way forward would be this:

1. Keep the current "nested" approach of encoding ADTs as the default.
2. Add support for a second, alternative "flat" encoding with a configurable "type" member name, in two stages:
- first: implement the "easy" but half-assed "type member must come first" support
- later: add a caching layer that allows for "look-ahead" to the type member, which then enables the flat encoding in its full form. This means that, for this feature, we give up the bounded memory guarantee but keep the single input-pass.

The docs would state that this "flat" encoding should be used only for compatibility reasons when the "other side" is not under ones own control.

**Comment by mushtaq** [comment]
It was nice to know the rationale for current design. Also agree with the summary of the next steps.

**Comment by mushtaq** [comment]
I thought of sharing the current pattern of organizing codecs for an ADT relevant for this ticket:

```scala
sealed trait Adt
case class Hello(name: String) extends Adt
case class Square(number: Int) extends Adt

implicit def adtCodec[T <: Adt]: Codec[T] = explicitAdtCodec.asInstanceOf[Codec[T]]

lazy val explicitAdtCodec: Codec[Adt] = {
  @silent implicit lazy val helloCodec: Codec[Hello]   = deriveCodec[Hello]
  @silent implicit lazy val squareCodec: Codec[Square] = deriveCodec[Square]
  deriveCodec[Adt]
}
```

If I do not follow this pattern, a lot of time goes in figuring out unintended errors due to mismatch of how `Hello` is encoded/decoded.
 
This is a common error due to how things are sent vs received as shown below:

```scala
def receive[T: Decoder](x: String): T = null.asInstanceOf[T]
receive[Adt]("incoming Hello or Square data...")

def send[T: Encoder](x: T): Unit = {}
send(Hello("abc")) //without the above pattern, helloCodec is used which is unintended
send(Square(100))  //without the above pattern, helloCodec is used which is unintended
```
Maybe, valid concerns to address for the current ticket.

**Comment by sirthias** [comment]
Yes, we also use the

```scala
implicit val superTypeCodec = {
  implicit val a = deriveCodec[SubTypeA]
  implicit val b = deriveCodec[SubTypeB]
  deriveCodec[SuperType]
}
```

pattern, which looks good an clear to me.
For now I would say that that's the best way to go.
