### ISSUE TITLE
Scala 2.12 support in 1.7+?

### ISSUE THREAD

**Issue by PawelLipski** [sirthias/borer#389]
Is there going to be Scala 2.12 support in 1.7+ versions? AFAICS the last 2.12-compatible version was 1.6.3 ☹️

**Comment by PawelLipski** [comment]
I see that changelog for 1.7.0 says `removed support/cross-building for Scala 2.12`... has there been an obstacle in further support of 2.12?

**Comment by sirthias** [comment]
I removed support for Scala 2.12 in the upgrade to 1.7.0 because it was initially planned to cross-build 1.7.0 also against Scala 3 and I hit some road block where 2.12 support was a pain.
Therefore I removed 2.12 support in order to simplify the build.

However, I later decided to move Scala 3 out into its own branch and _not_ go for cross-building.
Therefore it should be easy to just revert the commit that removed 2.12 support.

**Comment by PawelLipski** [comment]
We'd be grateful if you could re-add the 2.12 support in a 1.7.3 release, our project is still kinda-stuck at Scala 2.12 :/

**Comment by sirthias** [comment]
Ok, will try to get that done sometime in the next days...

**Comment by sirthias** [comment]
Just released 1.7.2 with Scala 2.12 cross-building re-enabled...
