### ISSUE TITLE
Support scala 3

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#480]
I think this mainly applies to the derivation module because macros will need to be rewritten.

**Comment by sirthias** [comment]
Thank you, @mushtaq!
I am on that.
With low prio at this point but the migration to Scala 3 is on my radar.

**Comment by martinring** [comment]
Hey @sirthias, would you accept any help with the scala 3 migration? I'd love to get involved.

**Comment by sirthias** [comment]
Hey Martin,
thanks for raising your hand!
I'm feeling the pressure on this ticket myself, but have so far refrained from diving in head first in order to not throw my new years resolution "focus more on the actual important in your life" right out of the window in the first days of January... :)

I've already played around with Scala 3 support sometime last year and managed to get cross-building across 2.12, 2.13 and 3 set up and working fine for all modules except `derivation`.

As the derivation logic is somewhat involved and produces quite optimized code the macros aren't the easiest to migrate. If you want to jump in, I'd be happy to look at PRs and help where I can.

One thing that might help a great deal is https://github.com/sirthias/macrolizer.
Maybe we should first release that for Scala 3 in order to help with development and debugging?

**Comment by plokhotnyuk** [comment]
Hey Mathias,

[Here](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros) is a great example of derivation macros migration from Scala 2 to Scala 3. 

All credits to @rssh - he made it source compatible between Scala 2 and 3 versions to be tested by [the same test sources](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala) except [special cases for new enums](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodeMakerNewEnumSpec.scala).

**Comment by sirthias** [comment]
Thank you, @plokhotnyuk!
I'll take a look at it.
I'm currently planning on starting with the port to Scala 3 later this month, although I probably won't go for a cross-compiling setup.
I'll simply bump the version number and make a full jump to Scala 3...

**Comment by mushtaq** [comment]
@sirthias Came across this note in Scala [3.1.1 release](https://www.scala-lang.org/blog/2022/02/01/scala-3.1.1-released.html):

> Dual Scala 2/3 macros can be now declared in non-experimental scopes ([PR #13795](https://github.com/lampepfl/dotty/pull/13795)).

But as a user of this lib, I am ok if you want to release say `borer-2.0.0` only for Scala-3. 
I do not see any issue in keep using 1.7.2 version for those who remain on Scala 2.13.

**Comment by OndrejSpanel** [comment]
I am interested in Scala 3 version, as Borer is one of the last few major dependencies blocking my project from upgrading.

Is there anything I could do to help this happen (work on some issues, sponsoring...)?

**Comment by sirthias** [comment]
@OndrejSpanel We are in the same position as you, with borer being the last dependency holding us back from Scala 3 upgrade.
So, I've been investing a few hours last week to make it happen and made good progress.
There is only one last thing missing in the derivation macro work but I expect to be able to cut at least an initial Scala 3 version until Friday.
Which modules are you depending on?
Only core and derivation, I assume?

**Comment by OndrejSpanel** [comment]
Exactly, core and derivation.

That is really great news.

If there is some way I could help, please let me know. Otherwise I stay looking forward to the version.

**Comment by sirthias** [comment]
Ok, quick status update:
ArrayBasedCodecs are passing all tests and MapBasedCodecs and completely implemented.
I'm in the process and enabling all tests, one by one, cleaning up, etc.
However, I have to stop right now because I'm about to take off to a two week family vacation.
So, unfortunately, no release yet.

But, there is not much missing, maybe two or three hours more before a first release for Scala 3.
I've pushed my current state to the `scala-3` branch, if anyone wants to take a look.
(I'm currently in the middle of moving the tests in the `derivation3` module from uTest to mUnit, they aren't compiling right now...)

I'll finish this all up when I get back in two weeks and will definitely publish a release then.
Cheers!

**Comment by OndrejSpanel** [comment]
Great news. Thanks for letting us know on the progress, so that we can tune our migration plans accordingly.

Enjoy your holiday.

**Comment by sirthias** [comment]
Another update. The Scala 3 macros are finally done.
Everything is implemented and all tests are passing.
It took a while longer, as always, also due to more compiler bugs that I had to work around.

Now the only thing missing is packaging and releasing, which I hope I'll be able to complete on Monday.

**Comment by sirthias** [comment]
Got held back by real world priorities but did not forget this ticket... :)
I just pushed a couple more commits separating the scala2 build into its own branch.
From now on the master will be scala 3 only.

Now aiming for Tuesday as release day for the the scala 3 artifacts.
I'm sorry for the constant delays but I guess you know how it is...

**Comment by mushtaq** [comment]
Hey @sirthias I so much appreciate you regularly updating the progress on this ticket!

Even though my current work does not involve migrating to Scala3, I am keenly reading these and feel really excited 🎉 

Thank you so much for all your work.

**Comment by sirthias** [comment]
And it's finally done!
I just published borer 1.10.0 to sonatype. Should appear on Maven Central shortly.
1.10.0 is Scala-3-only. The latest version for Scala 2.13 is 1.8.0.
Thank you for sticking with me this long.
This migration really was quite some work and I'm glad to finally get it out the door.
I've refrained from changing to API too much from the previous version to make the upgrade easier.
Scala 3 gives us quite a few more options with regard to API design that I might pursue at some point in the future.
So far the idea was simply to get something released that gets the job done...

Please report any issues you find!
