### ISSUE TITLE
Best way to write a "Codec[Any]"

### ISSUE THREAD

**Issue by phdoerfler** [sirthias/borer#572]
This is a bit of a silly issue for a pet project of mine. I am afraid it has gotten a bit long, but I wanted to share what research I have done.

I wrote a simple akka-persistence journal plugin using Borer, but it can only write and read Strings currently. Typically, akka-persistence plugins support `Any` and not just `String` and I want to take my plugin to the next level and make it support this, too. I could easily do so by using, e.g., java serialization to turn any object into bytes and then use borer to encode and decode that to json.
However, the whole idea of the plugin is that it should be easy to look at the resulting json so this won't do.

Basically, I need a Codec for this type:

```scala
case class Record(writerUuid: String, persistenceId: String, sequenceId: Long, data: Any)
```

I see three options:
a) Use gson or jsoniter to turn the `Any` into json using reflection and then somehow tie that into borer
b) Stop using borer and just use gson or jsoniter for everything
c) Do **not** support `Any` but instead make the user supply their own Codec for the type they want to encode and decode *during runtime*.

I am of two minds about this. Option a) would certainly be the most convenient for the user, but option c) is probably the most reliable. I don't want to explore option b) because I'd rather learn about borer than about the other libraries.

One easy way to implement a) would be to take the gson/jsoniter generated json, turn it into a string and just write that using borer (and vice versa). But that won't look pretty and this is a toy project anyway, so let's entertain the hard way.

It is easy to turn any object into json using reflection and gson:

```scala

import com.google.gson._
import io.doerfler._

val obj = CaseStudent("Casey", 32);
// obj: CaseStudent = CaseStudent(name = "Casey", age = 32)

val gson: Gson = new GsonBuilder().setPrettyPrinting().create();
// gson: Gson = …
val json = gson.toJson(obj)
// json: String = """{
//   "name": "Casey",
//   "age": 32
// }"""
val parsed = JsonParser.parseString(json)
// parsed: JsonElement = {"name":"Casey","age":32}
val obj2 = gson.fromJson(parsed, classOf[CaseStudent])
// obj2: CaseStudent = CaseStudent(name = "Casey", age = 32)
obj == obj2
// res0: Boolean = true
```

To implement option a) I could potentially:
a.a) Use borer's [DOM](https://sirthias.github.io/borer/borer-core/DOM.html)
a.b) Write an own manual encoder / decoder pair
a.c) To use [Transcoding](https://sirthias.github.io/borer/borer-core/transcoding.html)

Options a.a) and a.c) seem a bit overkill for this pet project as I am not familiar with either of them.
Option a.b) meanwhile might look like this:

```scala
implicit val encoder: Encoder[Record] = Encoder { (writer, rec) =>
  writer
    .writeArrayOpen(4)
    .writeString(rec.writerUuid)
    .writeString(rec.persistenceId)
    .writeLong(rec.sequenceId)
    .writeAny(rec.data) // <------- Integrate with gson / jsoniter
    .writeArrayClose()
}

implicit val decoder: Decoder[Record] = Decoder { reader =>
  val unbounded = reader.readArrayOpen(4)
  val rec = Record(
    reader.readString(),
    reader.readString(),
    reader.readLong(),
    reader.readAny() // <------- Integrate with gson / jsoniter
  )
  reader.readArrayClose(unbounded, rec)
}
```

This is the approach I'd use if I wanted to rely on, e.g., java serialization or just embed the json produced by gson or jsoniter.
Ideally though, I'd have the json in here as a first class citizen and not embedded in a string.
Unfortunately, I am not familiar at all with borer's low level API (the code responsible for, e.g., `writeLong`).

c.a) In contrast, option c) could be implemented using [derivation](https://sirthias.github.io/borer/borer-derivation/index.html):
```scala
case class Record[T](writerUuid: String, persistenceId: String, sequenceId: Long, data: T)
```

And have the user supply `Encoder[T]` and `Decoder[T]`. This is more hassle for the user because they have to bring their own codec but it comes with a few advantages: Speed and stability and it might be the easiest to implement (I have not toyed around with this enough to be sure, though). Speed is certainly not a hard requirement. I doubt this plugin will ever see production use, but I hope it will be helpful for developing apps that use akka-persistence.

@sirthias In any case, thanks for this great library. I'd appreciate if you could share your thoughts on this endeavor!

**Comment by sirthias** [comment]
Ok, Philipp, let's take a step back and look at your overall requirements first.

When choosing a serialization approach for an application usually the following factors are the most important:

1. Interoperability
Who is supposed to decode what you encode? Just your own application/system or other systems that are potentially outside of your control?
Same on the reading side: Are you only decoding your own encodings or do you need to be able to deserialize bytes that other applications (e.g. clients) have encoded?

2. Durability
Are the serializations more or less "transient" (e.g. in a client/server protocol interaction) or does your system need to be able to deserialize bytes that have been encoded potentially years prior? In the latter case long-term evolvability / versioning becomes a crucial part of the whole approach!

3. Efficiency
Both spacial and temporal efficiency is often a requirement but usually not the foremost priority.

4. Self-Describability
IMHO this is often underrated. Protobuf bytes, for example, are completely inscrutable if you don't have the schema information for them.
When picking a serialization approach it's important to think about how you are going to manage schema evolution in the long-term, if the encoded format doesn't include structure information. JSON and CBOR are easier in that regard because they describe themselves on the lowest level, which doesn't mean though, that they contain _everything_ your application needs to properly deserialize them!


Borer implements CBOR and JSON, which are both properly defined, "standard" formats, which help with (1) and (2) above.
However, by relying on reflection or full auto-deriving "magic" you give up a lot of control, which can make proper versioning quite hard!
(1) and especially (2) are going to be a challenge in any real application with such an approach.
For example, what happens if you would like to add, remove or rename a field in some class deep down in your model? By relying on reflection it's going to be difficult to maintain all the history of how a field _used to be_ called 2 years earlier.

Regarding (3) _borer_ is quite alright, especially on the CBOR side. But you'll probably be fine with any of the other available scala libs for JSON as well here.
(4) isn't really an issue with _borer_ as CBOR as well as JSON are "self-describing" in the basic sense.

Now to your `Codec[Any]` question:
One of _borer_'s strength is the quite fine control that is gives you over what exactly you'd like to be derived and what you'd like to define manually.
With a `Codec[Any]` _borer_ cannot help you at all. Derivation is off the table. You are in "define-everything-manually-or-rely-on-reflection-land".
If you really need a `Codec[Any]` I wouldn't use _borer_ at all since it doesn't really much value beyond the raw low-level layer of understanding JSON and CBOR.
And if you don't need CBOR I'd rather go for another serialization lib.

Also, I personally wouldn't mix or stack two different serialization libs when you can also get away with a single one.

So, to sum up:
_borer_ is heavily targeted towards idiomatic scala, which is a typeclass-based approach to serialization.
The compiler helps where you'd like it to and you get proper compile-time errors for all missing codecs.
No reflection, no runtime errors, no "super-macros" that claim to solve everything automatically and are hard to debug and to properly reign in.

> And have the user supply Encoder[T] and Decoder[T]. This is more hassle for the user because they have to bring their own codec but it comes with a few advantages...

In fact, this is not a hassle at all! It's exactly what I would expect!
I would like to have control over how my type `T` is supposed to be (de)serialized, because it's a key piece of logic once you think about longer-term evolution outside of toy projects!
And if I really don't care I can simply say

`implicit val fooCodec = deriveCodec[Foo]`

and have the compiler apply the default logic.
Then, later, I can always switch to any other logic _for this specific type_ (which might be somewhere deep in my model hierarchy), while everything else stays what it is.

Embrace the `Codec[T]` !! :)

**Comment by phdoerfler** [comment]
First of all, thanks a lot for your detailed reply!
About your questions:
1. Only my own application
2. Data does not need to survive multiple years, it's okay if the format changes from one day to another.
3. Definitely not a priority here
4. Very important! That's why I went for JSON

I do agree with all the points you bring up. This is really just a toy library for fun and maybe to help developers visualize what they are storing in their event sourcing journal for a short time.
Once they have seen what they wanted to see they would best be advised to switch to a different storage backend again.

The event sourcing implementation I'm writing this for, akka persistence, requires a event journal plugin to be able to serialize `AnyRef`, hence the need for `Codec[Any]`. I know Borer wasn't made for this and, again, for anything serious I would absolutely prefer hand written Codecs. But I was hoping I could perhaps coerce Borer into it because I otherwise really like the library.

This being said, I have run into further complications with akka persistence since I wrote this issue. I was hoping I'd find the time to deal with those and then have a more insightful reply. Alas, my spare time has recently been a bit on the short side.
